language: go

services:
  - docker

before_install:
  - curl -L --output mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.3.0/mkcert-v1.3.0-linux-amd64
  - chmod +x mkcert
  - ./mkcert abtercms.test "*.abtercms.test"
  - mv abtercms.test+1* ./docker/nginx/certs/
  - docker-compose pull
  - docker-compose up -d

install:
  - docker-compose exec php make install

script:
  - docker-compose exec php make build

after_success:
  - curl -L --output php-coveralls.phar https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - curl -L --output phpcov.phar https://phar.phpunit.de/phpcov.phar
  - chmod +x phpcov.phar php-coveralls.phar
  - mkdir ./tmp/cov
  - ./vendor/bin/phpunit -c vendor/abterphp/framework/phpunit.xml --coverage-php ./tmp/cov/framework.cov
  - ./vendor/bin/phpunit -c vendor/abterphp/admin/phpunit.xml --coverage-php ./tmp/cov/admin.cov
  - ./vendor/bin/phpunit -c vendor/abterphp/website-creative/phpunit.xml --coverage-php ./tmp/cov/website-creative.cov
  - ./vendor/bin/phpunit -c vendor/abterphp/bootstrap4-website/phpunit.xml --coverage-php ./tmp/cov/bootstrap4-website.cov
  - ./vendor/bin/phpunit -c vendor/abterphp/website/phpunit.xml --coverage-php ./tmp/cov/website.cov
  - ./vendor/bin/phpunit -c vendor/abterphp/contact/phpunit.xml --coverage-php ./tmp/cov/contact.cov
  - ./vendor/bin/phpunit -c vendor/abterphp/files/phpunit.xml --coverage-php ./tmp/cov/files.cov
  - ./vendor/bin/phpunit -c vendor/abterphp/propeller-admin/phpunit.xml --coverage-php ./tmp/cov/propeller-admin.cov
  - ./phpcov.phar merge -vvv --clover tmp/clover.xml tmp/cov/
  - travis_retry ./php-coveralls.phar -v --coverage_clover=./tmp/clover.xml --json_path=./tmp/coveralls-upload.json
