language: go

services:
  - docker

before_install:
  - curl -L --output mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.3.0/mkcert-v1.3.0-linux-amd64
  - chmod +x mkcert
  - ./mkcert abtercms.test "*.abtercms.test"
  - mv abtercms.test+1* ./docker/nginx/certs/
  - docker-compose pull
  - docker-compose up -d

install:
  - docker-compose exec php make install

script:
  - docker-compose exec php make build

after_success:
  - curl -L --output php-coveralls.phar https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - curl -L --output phpcov.phar https://phar.phpunit.de/phpcov.phar
  - chmod +x phpcov.phar php-coveralls.phar
  - mkdir ./tmp/cov
  - docker-compose exec php make coverage
  - docker-compose ./phpcov.phar merge -vvv --clover tmp/report/clover.xml tmp/cov/
  - docker-compose ./php-coveralls.phar -v --coverage_clover=./tmp/report/clover.xml --json_path=./tmp/coveralls-upload.json
  - travis_retry docker-compose exec php make coverage
  - rm -rf ./tmp/cov
