version: '3'
services:
  db_test:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=85TKjy8ZnYGpThBTfYAv
      - MYSQL_DATABASE=abter_test
      - MYSQL_USER=abter_test
      - MYSQL_PASSWORD=abter_test
      - MYSQL_PORT=3306
    volumes:
      - ./docker/mysql/dumps:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    ports:
      - "3376:3306"

  memcached_test:
    image: memcached:alpine
    ports:
      - "11281:11211"

  redis_test:
    image: redis:alpine
    ports:
      - "6449:6379"

  php_test:
    image: abtercms/php:72
    links:
      - db_test
      - memcached_test
      - redis_test
    volumes:
      - .:/website
      - ./docker/php/conf.d/zzz.ini:/usr/local/etc/php/conf.d/zzz.ini:ro
    working_dir: /website

  nginx_test:
    image: nginx
    links:
      - php_test
    volumes:
      - .:/website
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    working_dir: /website
